### ISSUE TITLE
Allow passing of rsync parameters

### ISSUE THREAD

**Issue by icecaster** [heyday/beam#53]
Would be great if rsync parameters could be passed on a per server basis, eg

```
"servers": {
    "test": {
        "user": "user",
        "host": "some.hostname",
        "webroot": "subdomains/staging",
        "rsync-params": "--no-perms"
    }
}
```

**Comment by stecman** [comment]
@icecaster can you give some more detail on your use case for this? What kind of constraints/setup do you have that requires this? If it's a common, general problem it's possibly better to add an option in Beam for it.

**Comment by icecaster** [comment]
Hey @stecman 
My use case is that the files & folders in the web root of my server should be owned by the web user (www-data) - not the deployment user. 
Rsync will try to apply same permissions as per git, which causes it to fail, throwing errors.

**Comment by stecman** [comment]
Hmm, do you have an error message example? Also, is this solved for you by using `--no-perms`, or is that a random example?

There's a known issue with target directory permissions being synced, which causes an error if the user doesn't have permission to change the mode of the target folder. We technically shouldn't be syncing that permission as it's not from the repository.

**Comment by icecaster** [comment]
This would be related to this issue, setting permissions on parent directory:

![Uploading Screenshot from 2017-07-04 14:36:34.png…]()

I could also see this being an issue when 2 different users are deploying to the same target

**Comment by stecman** [comment]
I've had a look at possible solutions/workarounds for this, and it doesn't look like there's a quick change we can make to skip permission syncing on the target directory.

* As far as I can tell, Rsync doesn't have a way to selectively sync permissions at all, and doesn't provide a way to specify the root/target directory in a filter/exclude rule.
* Syncing directorie contents (`source/`) appears to be required for deletion of files that are missing from the source but exist on the target. Syncing explicit files from the source (`source/*`) doesn't delete removed files from the target, and specifying the missing files on the source side causes rsync to error.

Adding an option in the Beam config to not sync permissions is my vote to solve this, since there's more than one case where syncing them isn't required/desired:

* Permissions on the root directory differ between source and target and the target directory is not owned by the ssh user (your case)
* Permissions disabled in Git (`git config core.fileMode false`). The permissions from `git archive` are inherited from the source system and aren't really meaningful.
* The target system has a different umask to the source and this needs to be honoured. For example Some shared hosting will refuse to serve PHP files that have group write permission, which currently requires a Beam command to `chmod` before deploying.
* Custom acls (eg. `setfacl`) or some other permissions scheme is in use on the target that specifies how permissions are inherited.

How about this?

```js
{
    "servers": [
        {
            // ...
            "permissions": false
        }
    ]
}
```
FWIW I'm reluctant to add an equivalent to the `--args` option in the config, since that option was intended as more of a debugging/workaround tool than something for permanent solutions.

**Comment by icecaster** [comment]
Agree with your points.

Only change suggested would be naming the config variable "syncPermissions"

**Comment by icecaster** [comment]
Awesome, thanks!
